# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: One Aware Being
email: oneawarebeing@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The only unquestionable experience is our Being and the Knowing of it.
  In order to experience a World collectively our Aware Being has to be One and the same.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://matyasmarkovics.github.io" # the base hostname & protocol for your site
#twitter_username:
#github_username:  matyasmarkovics

# Build settings
markdown: kramdown
